base_dir: '/Users/ramya/University/misc/AirObject_trials/test_on_their_test' # Directory with images, segmentations and superpoint features
output_dir: '/Users/ramya/University/misc/AirObject_trials/test_on_their_test/output' # Directory to save global tracking results
save_video: False # Save tracking video
video_path: '' # Output path for tracking video
match_threshold:  # [-1.0 to 1.0]
###
method: 'airobj_single_frame' # ['airobj', 'airobj_single_frame', 'airobj_single_frame_track']
# 'airobj_single_frame': AirObject Single Frame Descriptors
# 'airobj_single_frame_track': AirObject Single Frame Descriptors - Updating the Global Object Dictionary as the objects are tracked
# 'airobj': AirObject Temporal Descriptors
airobj_model_path: '/Users/ramya/University/misc/AirObject/models/airobject_model.pth'
model:
  airobj:
    descriptor_dim: 256
    points_encoder_dims: [2, 4, 8, 16]
    hidden_dim: 512
    dropout: 0
    alpha: 0.2
    nheads: 4
    nout: 2048
    temporal_encoder_dim: 2048 # AirObject
    temporal_encoder_out_dim: 2048
    temporal_kernel_size: 1